import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Online Market",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-500">{children}</body>
    </html>
  );
}
